version: "3"

services:
    mongodb:
        image: mongo:4.4.4
        container_name: mongo-db-product
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        volumes:
            - mongodb-data-product:/data/db
        networks:
            - mongodb_network_product
        ports:
            - ${MONGO_PORT}:27017
        restart: unless-stopped
    redis:
        image: redis
        container_name: redis-db-product
        volumes:
            - redis-data-product:/data/redis
        networks:
            - redis_network_product
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: always
    api:
        build: .

volumes:
    mongodb-data-product:
    redis-data-product:

networks:
    mongodb_network_product:
        driver: bridge
    redis_network_product:
        driver: bridge
