version: "3"

services:
    mongodb:
        image: mongo:4.4.4
        container_name: mongo-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        volumes:
            - mongodb-data:/data/db
        networks:
            - mongodb_network
        ports:
            - ${MONGO_PORT}:${MONGO_PORT}
        restart: unless-stopped
    redis:
        image: redis
        container_name: redis-db
        volumes:
            - redis-data:/data/redis
        networks:
            - redis_network
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: always
    api:
        build: .

volumes:
    mongodb-data:
    redis-data:

networks:
    mongodb_network:
        driver: bridge
    redis_network:
        driver: bridge
