version: "3"

services:
    mongodb:
        image: mongo:4.4.4
        container_name: mongo-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=qweasdQWEASD
        volumes:
            - mongodb-data:/data/db
        networks:
            - mongodb_network
        ports:
            - 27017:27017
        restart: unless-stopped
    redis:
        image: redis
        container_name: redis-db
        volumes:
            - redis-data:/data/redis
        networks:
            - redis_network
        ports:
            - 6379:6379
        restart: always
    api:
        build: .

volumes:
    mongodb-data:
    redis-data:

networks:
    mongodb_network:
        driver: bridge
    redis_network:
        driver: bridge
